# Generated by Django 4.2.11 on 2024-04-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default='Developer', max_length=100, verbose_name='Service name'),
        ),
    ]
